#!/usr/bin/env perl
use strict;
use warnings;

use Cwd qw(abs_path);
use File::Basename qw(dirname);

my $script_dir = dirname(abs_path($0));
my $repo_root  = abs_path("$script_dir/..");
my $sys_header = "$repo_root/include/syscall.h";
my $output_file = "$repo_root/user/usys.S";

open my $header_fh, '<', $sys_header
  or die "Failed to open $sys_header: $!\n";

my @syscalls;
while (my $line = <$header_fh>) {
    if ($line =~ /^\s*#define\s+SYS_(\w+)\s+\d+/) {
        push @syscalls, $1;
    }
}
close $header_fh;

die "No SYS_ definitions found in $sys_header\n" unless @syscalls;

my @lines = (
    "# generated by scripts/gen_usys.pl - do not edit",
    "# based on include/syscall.h SYS_xxx definitions",
    "",
    "#include \"syscall.h\"",
    "",
    "# each __sys_xxx stub loads a7 with the syscall id,",
    "# invokes ecall, and returns the kernel result.",
    "",
);

for my $name (@syscalls) {
    push @lines,
        "# --- ${name}() ---",
        "\t.global __sys_${name}",
        "__sys_${name}:",
        "\tli a7, SYS_${name}",
        "\tecall",
        "\tret",
        "";
}

open my $out_fh, '>', $output_file
  or die "Failed to write $output_file: $!\n";
print {$out_fh} join("\n", @lines) . "\n";
close $out_fh;

printf "Generated %s for %d syscalls\n",
  substr($output_file, length($repo_root) + 1),
  scalar @syscalls;
